### ISSUE TITLE
tf.session

### ISSUE THREAD

**Issue by sonnguyen129** [munnafaisal/Diabetic_retinopathy_gradcam#1]
I know that tf.Session is remove in tensorflow 2.x. Can you explain me this? What advantage of tf.Session? Thank you
```
graph2 = tf.Graph()
with graph2.as_default():    
 global model2,session2   
 session2 = tf.Session()    
 with session2.as_default():        
  K.set_session(session2)       
  model2= None        
  model2 = load_model("./intl10.h5", compile=True)
```

**Comment by munnafaisal** [comment]
The project is using legacy TensorFlow 1.x  for model dependency where Session is the only option to run tensor operations. However, Tensorflow Session is also available in TensorFlow 2.x. Pls visit the following link for more details.  

https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session
https://joddiy.github.io/2020/05/07/TF2-0-Function/

Anyway for deploying a trained model as a service creating TensorFlow graphs and variables over each API call is not a good idea. tf.Session can maintain a global state. I did not test this project for @tf.function decorator as an alternative of tf.Session for TF 2.x. You can try that....!!  

Thanks

Md. Faisal Ahmed Siddiqi

**Comment by sonnguyen129** [comment]
Thank you so much. I will close this issue
